import type { User, Speaker, AgendaItem, Question } from './types';
import { PlaceHolderImages } from './placeholder-images';

const speakerImages = PlaceHolderImages;

export const speakers: Speaker[] = [
  {
    id: '1',
    name: 'Dr. Ángel García',
    specialty: 'Cardiología',
    bio: 'Internista, cardiólogo, epidemiólogo, especialista en falla cardiaca y trasplante cardiaco.',
    imageUrl: '/speaker-angel-garcia.png',
    imageHint: 'Dr. Ángel García',
    qualifications: [
      'Internista, cardiólogo, epidemiólogo, especialista en falla cardiaca y trasplante cardiaco.',
      'Presidente del capítulo cardiometabólico de la SCC.',
      'Jefe de cardiología del HUSI y director del programa de especialización en cardiología de la PUJ.'
    ],
  },
  {
    id: '2',
    name: 'Dra. Laura Duque',
    specialty: 'Cardiología',
    bio: 'Especialista en Medicina Interna y Cardiología, Universidad CES',
    imageUrl: '/speaker-laura-duque.png',
    imageHint: 'Dra. Laura Duque',
    qualifications: [
      'Especialista en Medicina Interna y Cardiología, Universidad CES',
      'Estudios avanzados en Insuficiencia Cardíaca, Universidad UPB',
      'Estudios avanzados en Dislipidemias, EAS Cardióloga clínica, PULS.OS',      
      'Jefe del Posgrado de Cardiología, Universidad CES',
      'Presidente Seccional Antioquia, SCC'
    ],
  },
  {
    id: '3',
    name: 'Dr. Germán Camilo Giraldo',
    specialty: 'Cardiología',
    bio: 'Especialista en Medicina Interna, Universidad de Caldas',
    imageUrl: '/speaker-german-giraldo.png',
    imageHint: 'Dr. Germán Camilo Giraldo',
    qualifications: [
      'Especialista en Medicina Interna, Universidad de Caldas',
      'Especialista en Cardiología, ICESI - Fundación Valle del Lili',
      'Doctor en Ciencias de la Salud (Énfasis en DMT2 y Enfermedad Cardiovascular)',
      'Formación Especializada en ECMO, Fundación Cardiovascular',
      'Cardiólogo Clínico, Todo por el corazón',
      'Co-Investigador, Internistas de Caldas',
      'Docente de Posgrado, Universidad de Caldas'
    ],
  },
  {
    id: '4',
    name: 'Dr. Javier Arango',
    specialty: 'Nefrología',
    bio: 'Médico internista - Nefrólogo',
    imageUrl: '/speaker-javier-arango.png',
    imageHint: 'Dr. Javier Arango',
    qualifications: [
      'Médico internista - Nefrólogo',
      'MBA',
      'Expresidente ACMI'
    ],
  },
  {
    id: '5',
    name: 'Dra. Claudia Monsalve',
    specialty: 'Endocrinología',
    bio: 'Medicina Interna, UPB - Endocrinología, UPB',
    imageUrl: '/speaker-claudia-monsalve.png',
    imageHint: 'Dra. Claudia Monsalve',
    qualifications: [
      'Medicina Interna, UPB - Endocrinología, UPB',
      'Profesora Titular y Coordinadora de la Especialización en Endocrinología, UPB',
      'Actividad Clínica en: Clínica Universitaria Bolivariana y Clínica Las Américas AUNA',
      'Pertenencia a Sociedades Científicas (ACE, ACMI, SCC, EAS)'
    ],
  },
];

export const agendaItems: AgendaItem[] = [
  // DÍA 1 - Viernes 14 de noviembre de 2025
  {
    id: 'd1-1',
    date: '2025-11-14',
    startTime: '08:00',
    endTime: '08:10',
    topic: 'Bienvenida',
    speakerIds: ['1'],
    participants: ['Dra. Etna Liliana Valenzuela'],
    type: 'welcome',
    location: 'Hotel Hilton Cartagena de Indias',
  },
  {
    id: 'd1-2',
    date: '2025-11-14',
    startTime: '08:10',
    endTime: '08:25',
    topic: 'Una epidemia que late en silencio. Status Quo de la enfermedad CV en Colombia',
    speakerIds: ['1'],
    type: 'session',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Riesgo CV',
  },
  {
    id: 'd1-3',
    date: '2025-11-14',
    startTime: '08:25',
    endTime: '09:15',
    topic: 'Manos a la obra (estratificación personal del riesgo)',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Riesgo CV',
  },
  {
    id: 'd1-4',
    date: '2025-11-14',
    startTime: '09:15',
    endTime: '09:35',
    topic: 'Lo que no se mide, no se previene: el reto de ver el riesgo a tiempo',
    speakerIds: ['2'],
    type: 'session',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Riesgo CV',
  },
  {
    id: 'd1-5',
    date: '2025-11-14',
    startTime: '09:35',
    endTime: '09:50',
    topic: 'Q&A',
    speakerIds: ['1', '2', '3'],
    type: 'qna',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Riesgo CV',
  },
  {
    id: 'd1-6',
    date: '2025-11-14',
    startTime: '09:50',
    endTime: '10:05',
    topic: 'Coffee Back',
    speakerIds: [],
    type: 'break',
  },
  {
    id: 'd1-7',
    date: '2025-11-14',
    startTime: '10:05',
    endTime: '10:25',
    topic: 'Más allá de los números: el arte de interpretar el perfil lipídico',
    speakerIds: ['3'],
    type: 'session',
    moderator: 'Dra. Laura Duque',
    section: 'Dislipidemia',
  },
  {
    id: 'd1-8',
    date: '2025-11-14',
    startTime: '10:25',
    endTime: '10:45',
    topic: 'La ciencia de bajar el colesterol: terapias combinadas y estrategias personalizadas. ¡Cada miligramo cuenta!',
    speakerIds: ['1'],
    type: 'session',
    moderator: 'Dra. Laura Duque',
    section: 'Dislipidemia',
  },
  {
    id: 'd1-9',
    date: '2025-11-14',
    startTime: '10:45',
    endTime: '11:00',
    topic: 'Q&A',
    speakerIds: ['1', '3'],
    type: 'qna',
    moderator: 'Dra. Laura Duque',
    section: 'Dislipidemia',
  },
  {
    id: 'd1-10',
    date: '2025-11-14',
    startTime: '11:00',
    endTime: '11:50',
    topic: 'Taller de interpretación & tratamiento',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dra. Laura Duque',
    section: 'Dislipidemia',
  },
  {
    id: 'd1-11',
    date: '2025-11-14',
    startTime: '11:50',
    endTime: '12:15',
    topic: 'Coffee Break',
    speakerIds: [],
    type: 'break',
  },
  {
    id: 'd1-12',
    date: '2025-11-14',
    startTime: '12:15',
    endTime: '12:35',
    topic: 'Diagnosticar bien para tratar mejor: claves de las nuevas guías de hipertensión',
    speakerIds: ['3'],
    type: 'session',
    moderator: 'Dr. Ángel García',
    section: 'Hipertensión Arterial',
  },
  {
    id: 'd1-13',
    date: '2025-11-14',
    startTime: '12:35',
    endTime: '12:55',
    topic: 'Manejo integral de la hipertensión: evidencia, guías y práctica clínica',
    speakerIds: ['2'],
    type: 'session',
    moderator: 'Dr. Ángel García',
    section: 'Hipertensión Arterial',
  },
  {
    id: 'd1-14',
    date: '2025-11-14',
    startTime: '12:55',
    endTime: '13:10',
    topic: 'Q&A',
    speakerIds: ['2', '3'],
    type: 'qna',
    moderator: 'Dr. Ángel García',
    section: 'Hipertensión Arterial',
  },
  {
    id: 'd1-15',
    date: '2025-11-14',
    startTime: '13:10',
    endTime: '14:00',
    topic: 'Lo pides, te llegó y no sabes qué hacer',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dr. Ángel García',
    section: 'Hipertensión Arterial',
  },
  {
    id: 'd1-16',
    date: '2025-11-14',
    startTime: '14:00',
    endTime: '14:25',
    topic: 'Caso clínico integrador',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dr. Ángel García',
    section: 'Hipertensión Arterial',
  },
  {
    id: 'd1-17',
    date: '2025-11-14',
    startTime: '14:25',
    endTime: '14:30',
    topic: 'Cierre del día',
    speakerIds: [],
    type: 'closing',
  },
  {
    id: 'd1-18',
    date: '2025-11-14',
    startTime: '14:30',
    endTime: '15:30',
    topic: 'Almuerzo Restaurante Las Chivas',
    speakerIds: [],
    type: 'meal',
    location: 'Restaurante Las Chivas',
  },
  {
    id: 'd1-19',
    date: '2025-11-14',
    startTime: '19:30',
    endTime: '22:00',
    topic: 'Cena Lanzamiento: Noche blanca en La Marina',
    speakerIds: [],
    type: 'meal',
    location: 'La Marina (Hotel Hilton)',
  },
  // DÍA 2 - Sábado 15 de noviembre de 2025
  {
    id: 'd2-1',
    date: '2025-11-15',
    startTime: '08:00',
    endTime: '08:15',
    topic: 'Bienvenida',
    speakerIds: ['2'],
    type: 'welcome',
    location: 'Hotel Hilton Cartagena de Indias',
  },
  {
    id: 'd2-2',
    date: '2025-11-15',
    startTime: '08:15',
    endTime: '08:35',
    topic: 'Diabetes Mellitus, la realidad desde el consultorio',
    speakerIds: ['5'],
    type: 'session',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Diabetes Mellitus',
  },
  {
    id: 'd2-3',
    date: '2025-11-15',
    startTime: '08:35',
    endTime: '08:55',
    topic: 'Abordaje práctico del tratamiento de la DMT2: más allá de la glucosa',
    speakerIds: ['5', '3'],
    type: 'session',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Diabetes Mellitus',
  },
  {
    id: 'd2-4',
    date: '2025-11-15',
    startTime: '08:55',
    endTime: '09:10',
    topic: 'Q&A',
    speakerIds: ['5', '3'],
    type: 'qna',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Diabetes Mellitus',
  },
  {
    id: 'd2-5',
    date: '2025-11-15',
    startTime: '09:10',
    endTime: '10:00',
    topic: 'Taller práctico: casos clínicos & prescripción',
    speakerIds: ['5', '2', '1', '3'],
    type: 'workshop',
    moderator: 'Dr. Germán Camilo Giraldo',
    section: 'Diabetes Mellitus',
  },
  {
    id: 'd2-6',
    date: '2025-11-15',
    startTime: '10:00',
    endTime: '10:15',
    topic: 'Coffee Back',
    speakerIds: [],
    type: 'break',
  },
  {
    id: 'd2-7',
    date: '2025-11-15',
    startTime: '10:15',
    endTime: '10:35',
    topic: '¿En qué falla la Falla en Colombia?',
    speakerIds: ['3'],
    type: 'session',
    moderator: 'Dra. Laura Duque',
    section: 'Falla cardíaca',
  },
  {
    id: 'd2-8',
    date: '2025-11-15',
    startTime: '10:35',
    endTime: '10:55',
    topic: 'En Falla Cardíaca...trátela usted mismo',
    speakerIds: ['1'],
    type: 'session',
    moderator: 'Dra. Laura Duque',
    section: 'Falla cardíaca',
  },
  {
    id: 'd2-9',
    date: '2025-11-15',
    startTime: '10:55',
    endTime: '11:10',
    topic: 'Q&A',
    speakerIds: ['1', '3'],
    type: 'qna',
    moderator: 'Dra. Laura Duque',
    section: 'Falla cardíaca',
  },
  {
    id: 'd2-10',
    date: '2025-11-15',
    startTime: '11:10',
    endTime: '11:55',
    topic: 'Taller práctico: preguntas y respuestas en Falla',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dra. Laura Duque',
    section: 'Falla cardíaca',
  },
  {
    id: 'd2-11',
    date: '2025-11-15',
    startTime: '11:55',
    endTime: '12:20',
    topic: 'Coffee Break',
    speakerIds: [],
    type: 'break',
  },
  {
    id: 'd2-12',
    date: '2025-11-15',
    startTime: '12:20',
    endTime: '12:40',
    topic: 'Lo que siempre quise saber del riñón',
    speakerIds: ['4'],
    type: 'session',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-13',
    date: '2025-11-15',
    startTime: '12:40',
    endTime: '13:05',
    topic: 'Taller práctico de diagnóstico',
    speakerIds: ['4', '1'],
    type: 'workshop',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-14',
    date: '2025-11-15',
    startTime: '13:05',
    endTime: '13:25',
    topic: '¿Qué hacer cuando se eleva la creatinina?',
    speakerIds: ['4'],
    type: 'session',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-15',
    date: '2025-11-15',
    startTime: '13:25',
    endTime: '13:40',
    topic: 'Q&A',
    speakerIds: ['4'],
    type: 'qna',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-16',
    date: '2025-11-15',
    startTime: '13:40',
    endTime: '14:05',
    topic: 'Taller práctico de tratamiento',
    speakerIds: ['4', '1', '2', '3'],
    type: 'workshop',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-17',
    date: '2025-11-15',
    startTime: '14:05',
    endTime: '14:30',
    topic: 'Caso clínico integrador',
    speakerIds: ['2', '1', '3'],
    type: 'workshop',
    moderator: 'Dr. Ángel García',
    section: 'Enfermedad Renal Crónica',
  },
  {
    id: 'd2-18',
    date: '2025-11-15',
    startTime: '14:30',
    endTime: '15:30',
    topic: 'Almuerzo Restaurante Las Chivas',
    speakerIds: [],
    type: 'meal',
    location: 'Restaurante Las Chivas',
  },
  {
    id: 'd2-19',
    date: '2025-11-15',
    startTime: '19:30',
    endTime: '22:00',
    topic: 'Cena libre: Restaurante Las Chivas',
    speakerIds: [],
    type: 'meal',
    location: 'Restaurante Las Chivas (Hotel Hilton)',
  },
];

export const users: User[] = [
    { id: '1', name: 'Dr. Alice Johnson', medicalId: 'MD12345', city: 'New York', specialty: 'General Practice', email: 'alice.j@example.com' },
    { id: '2', name: 'Dr. Bob Williams', medicalId: 'MD67890', city: 'Los Angeles', specialty: 'Surgery', email: 'bob.w@example.com' },
    { id: '3', name: 'Dr. Carol White', medicalId: 'MD54321', city: 'Chicago', specialty: 'Dermatology', email: 'carol.w@example.com' },
];

export const questions: Question[] = [
  {
    id: '1',
    userName: 'Dr. Alice Johnson',
    speakerName: 'Dr. Emily Carter',
    question: 'What are your thoughts on the new Statin guidelines for primary prevention?',
    isAnswered: true,
    submittedAt: new Date('2024-05-20T10:00:00Z'),
  },
  {
    id: '2',
    userName: 'Dr. Bob Williams',
    speakerName: 'Dr. Ben Hanson',
    question: 'Is there any new research on using deep brain stimulation for treatment-resistant depression?',
    isAnswered: false,
    submittedAt: new Date('2024-05-20T11:30:00Z'),
  },
];
