import { SurveyData } from "@/lib/types";

export const defaultSurveyData: SurveyData = {
  survey_metadata: {
    event_name: "Evento Cardiometabólico",
    survey_version: "1.0",
    total_days: 2,
    days_dates: {
      day_1: "2025-11-14",
      day_2: "2025-11-15",
    },
    total_respondents: 0,
  },
  daily_responses: {
    day_1: {
      date: "2025-11-14",
      response_count: 0,
      conference_ratings: {
        "Dr. Ángel García": {
          specialty: "Cardiólogo",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dra. Laura Duque": {
          specialty: "Cardióloga",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dr. Germán Camilo Giraldo": {
          specialty: "Cardiólogo",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
      },
      practical_spaces_rating: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
      },
      incremental_learning: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 5,
      },
    },
    day_2: {
      date: "2025-11-15",
      response_count: 0,
      recommendation_likelihood: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
        nps_categories: {
          detractors: { count: 0, percentage: 0 },
          passives: { count: 0, percentage: 0 },
          promoters: { count: 0, percentage: 0 },
        },
      },
      conference_ratings: {
        "Dr. Ángel García": {
          specialty: "Cardiólogo",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dra. Laura Duque": {
          specialty: "Cardióloga",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dr. Germán Camilo Giraldo": {
          specialty: "Cardiólogo",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dra. Claudia Monsalve": {
          specialty: "Endocrinóloga",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
        "Dr. Javier Arango": {
          specialty: "Nefrólogo",
          ratings_distribution: {
            "1": { count: 0, percentage: 0 },
            "2": { count: 0, percentage: 0 },
            "3": { count: 0, percentage: 0 },
            "4": { count: 0, percentage: 0 },
            "5": { count: 0, percentage: 0 },
            "6": { count: 0, percentage: 0 },
            "7": { count: 0, percentage: 0 },
            "8": { count: 0, percentage: 0 },
            "9": { count: 0, percentage: 0 },
            "10": { count: 0, percentage: 0 },
          },
          average_rating: 0,
          total_votes: 0,
          max_rating: 10,
        },
      },
      practical_spaces_rating: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
      },
      incremental_learning: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 5,
      },
      campus_feedback: {
        would_participate_again: {
          yes: { count: 0, percentage: 0 },
          no: { count: 0, percentage: 0 },
          total_votes: 0,
        },
        suggested_topics: {
          topics_list: [],
          topics_frequency: {},
          total_suggestions: 0,
        },
      },
      pre_event_info_rating: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
      },
      logistics_rating: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
      },
      agenda_compliance_rating: {
        ratings_distribution: {
          "1": { count: 0, percentage: 0 },
          "2": { count: 0, percentage: 0 },
          "3": { count: 0, percentage: 0 },
          "4": { count: 0, percentage: 0 },
          "5": { count: 0, percentage: 0 },
          "6": { count: 0, percentage: 0 },
          "7": { count: 0, percentage: 0 },
          "8": { count: 0, percentage: 0 },
          "9": { count: 0, percentage: 0 },
          "10": { count: 0, percentage: 0 },
        },
        average_rating: 0,
        total_votes: 0,
        max_rating: 10,
      },
    },
  },
  analytics_metrics: {
    day_1_metrics: {
      avg_conference_rating: 0,
      avg_practical_spaces_rating: 0,
      avg_incremental_learning: 0,
      total_conference_ratings: 0,
      response_count: 0,
      satisfaction_rate: 0,
    },
    day_2_metrics: {
      avg_recommendation_score: 0,
      avg_conference_rating: 0,
      avg_practical_spaces_rating: 0,
      avg_incremental_learning: 0,
      avg_pre_event_info_rating: 0,
      avg_logistics_rating: 0,
      avg_agenda_compliance_rating: 0,
      participation_again_rate: 0,
      total_conference_ratings: 0,
      response_count: 0,
      nps_score: 0,
      satisfaction_rate: 0,
    },
    overall_metrics: {
      total_responses: 0,
      overall_satisfaction_score: 0,
      net_promoter_score: 0,
      average_conference_rating: 0,
      average_practical_rating: 0,
      participation_retention_rate: 0,
    },
  },
  timestamp: {
    created_at: "2025-11-14T00:00:00Z",
    updated_at: "2025-11-15T23:59:59Z",
  },
};

export const buildDefaultSurveyData = (): SurveyData =>
  JSON.parse(JSON.stringify(defaultSurveyData));

